name: First WorkFlow
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiple commands
        run: | 
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Hello World"
      - name: Error Step
        run: error